Fix issue can't locate node trajectory_publisher
After building as follows README, found following issue.
ERROR: cannot launch node of type [trajectory_publisher/trajectory_publisher]: can't locate node [trajectory_publisher] in package [trajectory_publisher]

This patch solves this issue by adding catkin_package() macro to CMakeList.txt.
The issue found to be recent change in CMakeList.txt in trajectory_publisher where removed catkin_simple macros, it seems catkin_simple package have been doing this job automatically.

Issue found & solution tested on new ROS workspace

Before this fix
~/ctrl_ws/devel/lib$ ls
geometric_controller  libgeometric_controller.so  pkgconfig  python2.7

After this fix
~/ctrl_ws/devel/lib$ ls
geometric_controller  libgeometric_controller.so  pkgconfig  python2.7  trajectory_publisher